[versions]
ksp = "1.9.0-1.0.12"
agp = "8.7.1"
kotlin = "1.9.0"
core-ktx = "1.12.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
lifecycle-version = "2.7.0"
activity-compose = "1.8.2"
compose-bom = "2024.01.00"
compose-nav-version = "2.7.6"
hilt = "2.48"
hilt-compose = "1.1.0"
room = "2.6.1"
coroutines = "1.8.0"
hamcrest = "2.2"
mockk-version = "1.13.9"
google-services-version = "4.4.1"
firebase-bom = "32.8.1"
play-services-auth = "21.2.0"
credentials-version = "1.2.2"
googleId = "1.1.1"
work-manager-version = "2.9.0"
kotlinxSerializationJson = "1.6.3"
androidxDataStore = "1.1.1"
coil = "2.7.0"
kotlin-result-v = "2.0.0"
accompanist-permissions-v = "0.36.0"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk-version" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
hamcrest = { group = "org.hamcrest", name = "hamcrest", version.ref = "hamcrest" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-version" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-version" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "compose-nav-version" }
material = { group = "androidx.compose.material", name = "material" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3" }
room = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-annotation-processor = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ext-coroutines = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android" }
coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "coroutines" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt-compose"}
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-compose" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hilt-compose" }
google-firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
google-firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
google-firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore-ktx" }
google-firebase-auth = { group = "com.google.firebase", name = "firebase-auth-ktx" }
google-play-services = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "play-services-auth" }
credentials = { group = "androidx.credentials", name = "credentials", version.ref = "credentials-version" }
credentials-play-services-auth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "credentials-version" }
google-identity-googleId = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleId" }
workmanager = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work-manager-version" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
androidx-dataStore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDataStore" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil"}
kotlin-result = { group = "com.michael-bull.kotlin-result", name = "kotlin-result", version.ref = "kotlin-result_v" }
kotlin-result-coroutines = { group = "com.michael-bull.kotlin-result", name = "kotlin-result-coroutines", version.ref = "kotlin-result-v" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist-permissions-v" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
googleServices = { id = "com.google.gms.google-services", version.ref = "google-services-version"}
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

